-- Add more sample jobs for better user experience
INSERT INTO public.jobs (title, company, location, type, description, stipend, skills, published_date) VALUES
('Frontend Developer Intern', 'TechStart Inc.', 'San Francisco, CA', 'Internship', 'Join our team to build modern web applications using React and TypeScript. You will work on user-facing features and learn from senior developers.', '$2000/month', ARRAY['React', 'TypeScript', 'CSS', 'JavaScript'], NOW() - INTERVAL '2 days'),
('Marketing Assistant', 'GrowthLab', 'New York, NY', 'Part-time', 'Support our marketing team with social media management, content creation, and campaign analysis. Perfect for marketing students.', '$18/hour', ARRAY['Social Media', 'Content Writing', 'Analytics', 'Canva'], NOW() - INTERVAL '1 day'),
('Data Science Intern', 'DataCorp', 'Austin, TX', 'Internship', 'Work with our data science team to analyze large datasets and build predictive models. Experience with Python and SQL preferred.', '$2500/month', ARRAY['Python', 'SQL', 'Machine Learning', 'Pandas'], NOW() - INTERVAL '3 days'),
('UX Design Intern', 'DesignStudio', 'Seattle, WA', 'Internship', 'Create user-centered designs for mobile and web applications. You will work on wireframes, prototypes, and user research.', '$2200/month', ARRAY['Figma', 'User Research', 'Prototyping', 'Adobe Creative Suite'], NOW() - INTERVAL '5 days'),
('Customer Success Intern', 'ServiceFirst', 'Chicago, IL', 'Internship', 'Help our customers succeed by providing excellent support and building relationships. Great communication skills required.', '$1800/month', ARRAY['Communication', 'Customer Service', 'CRM', 'Problem Solving'], NOW() - INTERVAL '1 week'),
('Backend Developer Intern', 'CloudTech', 'Boston, MA', 'Internship', 'Build scalable backend services using Node.js and databases. You will work on APIs and system architecture.', '$2400/month', ARRAY['Node.js', 'PostgreSQL', 'REST APIs', 'Docker'], NOW() - INTERVAL '4 days'),
('Content Creator', 'MediaHub', 'Los Angeles, CA', 'Part-time', 'Create engaging content for social media platforms and blogs. Must have creativity and understanding of digital trends.', '$20/hour', ARRAY['Content Creation', 'Social Media', 'Photography', 'Video Editing'], NOW() - INTERVAL '6 days'),
('Sales Development Representative', 'SalesForce Pro', 'Miami, FL', 'Part-time', 'Generate leads and qualify prospects for our sales team. Excellent opportunity to learn B2B sales.', '$16/hour + commission', ARRAY['Sales', 'Lead Generation', 'CRM', 'Communication'], NOW() - INTERVAL '2 weeks'),
('Mobile App Developer Intern', 'AppMakers', 'Denver, CO', 'Internship', 'Develop cross-platform mobile applications using React Native. Work on features that impact thousands of users.', '$2100/month', ARRAY['React Native', 'JavaScript', 'Mobile Development', 'API Integration'], NOW() - INTERVAL '1 day'),
('Product Management Intern', 'InnovateCo', 'Portland, OR', 'Internship', 'Work with product managers to define requirements, analyze user feedback, and help shape product roadmap.', '$2300/month', ARRAY['Product Management', 'User Research', 'Analytics', 'Agile'], NOW() - INTERVAL '3 days'),
('Graphic Design Assistant', 'Creative Agency', 'Nashville, TN', 'Part-time', 'Support our design team with creating marketing materials, logos, and brand assets for various clients.', '$17/hour', ARRAY['Adobe Illustrator', 'Photoshop', 'InDesign', 'Branding'], NOW() - INTERVAL '1 week'),
('Quality Assurance Tester', 'TestPro', 'Atlanta, GA', 'Part-time', 'Test software applications for bugs and usability issues. Detail-oriented individuals who enjoy breaking things to make them better.', '$19/hour', ARRAY['Software Testing', 'Bug Reporting', 'Attention to Detail', 'Testing Tools'], NOW() - INTERVAL '5 days');